<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Source generator properties -->
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\Generated</CompilerGeneratedFilesOutputPath>

    <!-- Disable XML doc file to avoid duplicate cache entries in OpenAPI source generator -->
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Atc.Rest.Api.SourceGenerator" Version="1.0.34" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="HostAgent.yaml" />
    <AdditionalFiles Include=".atc-rest-api-client-contracts" />
  </ItemGroup>

</Project>
